### ISSUE TITLE
ioredis instrumentation: support v5

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-js-contrib#978]
ioredis instrumentation [currently support versions '>1 <5'](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/cb915cfe018678060b014e1385fcefd0dc73c776/plugins/node/opentelemetry-instrumentation-ioredis/src/instrumentation.ts#L52).

[A new version 5 was published at 26/03/2022](https://www.npmjs.com/package/ioredis/v/5.0.0)

This issue is about adding support to the new version.

Renovate tests fails to compile with new version in #957 .
Some examples of the CI output:

```
src/instrumentation.ts:55:39 - error TS2339: Property 'prototype' does not exist on type 'typeof import("/home/runner/work/opentelemetry-js-contrib/opentelemetry-js-contrib/node_modules/ioredis/built/index")'.

55           if (isWrapped(moduleExports.prototype.sendCommand)) {
                                         ~~~~~~~~~

src/instrumentation.ts:56:40 - error TS2339: Property 'prototype' does not exist on type 'typeof import("/home/runner/work/opentelemetry-js-contrib/opentelemetry-js-contrib/node_modules/ioredis/built/index")'.

56             this._unwrap(moduleExports.prototype, 'sendCommand');
                                          ~~~~~~~~~

src/instrumentation.ts:59:27 - error TS2339: Property 'prototype' does not exist on type 'typeof import("/home/runner/work/opentelemetry-js-contrib/opentelemetry-js-contrib/node_modules/ioredis/built/index")'.

59             moduleExports.prototype,
                             ~~~~~~~~~

src/instrumentation.ts:63:39 - error TS2339: Property 'prototype' does not exist on type 'typeof import("/home/runner/work/opentelemetry-js-contrib/opentelemetry-js-contrib/node_modules/ioredis/built/index")'.

63           if (isWrapped(moduleExports.prototype.connect)) {
```

And many more

**Comment by nazarkulyk** [comment]
Can someone port instrument to get it work with ioredis v5 ?
