### ISSUE TITLE
Cannot find type definition file for 'generic-pool'

### ISSUE THREAD

**Issue by yannick-bonnefond** [open-telemetry/opentelemetry-js-contrib#1632]
### What version of `OpenTelemetry` are you using?
@opentelemetry/auto-instrumentations-node@0.38.0

### What version of `Node` are you using?
20.5.0

### What version of `Typescript` are you using?
5.1.6

### What did you do?
- Installed & setup opentelemetry node-sdk + auto-instrumentation-node  
- build with `npm run tsc`  

### What did you expect to see?
Build without error

### What did you see instead?
```
error TS2688: Cannot find type definition file for 'generic-pool'.
  The file is in the program because:
    Entry point for implicit type library 'generic-pool'
```

### Additional context
tsc build is working fine on version 4.8 of typescript but fails on 5.1

The error is likely caused by the `@types/generic-pool` on which depends the `@opentelemetry/instrumentation-generic-pool` package. 
Latest version `@types/generic-pool`  does not exports any typings anymore as the `generic-pool` package provides them directly.

Also, `@opentelemetry/instrumentation-generic-pool`  [imports @types/generic-pool as dependency](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-generic-pool/package.json#L66) and not `devDependency` which looks like a mistake. 

This is probably causing the issue with tsc on consumer projects using  `@opentelemetry/instrumentation-generic-pool` or the auto instrumentation

### Potential Solutions

1) Use typings from generic-pool package directly and remove the dependency to `@types/generic-pool`
2) Move the `@types/generic-pool` to devDependencies

**Comment by blumamir** [comment]
related PR: #1563 

> Also, `@opentelemetry/instrumentation-generic-pool` [imports @types/generic-pool as dependency](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-generic-pool/package.json#L66) and not `devDependency` which looks like a mistake.

This is not a mistake, it is required as the instrumentation package exports types that it imports from the types packages. If the types is not required as regular dependency, typescript fails to compile on end users applications. You can read more about it in the PR.
