### ISSUE TITLE
npm run compile fails on windows

### ISSUE THREAD

**Issue by Flarna** [open-telemetry/opentelemetry-js-contrib#680]
### What version of OpenTelemetry are you using?

Latest main

### What version of Node are you using?

14.18.0

### What did you do?

`npm install` which triggers `npm run compile`

### What did you expect to see?

success compilation

### What did you see instead?

compilation failed with `ERR! lerna Unknown arguments: pkg, get, name)`

### Additional context

Seems to be caused by #659 which added linux style arguments `$(npm pkg get name)` to precompile script

**Comment by dyladan** [comment]
Maybe we should replace it with a node script in scripts

**Comment by Flarna** [comment]
Or we just copy paste them module name.

**Comment by dyladan** [comment]
https://github.com/open-telemetry/opentelemetry-js-contrib/pull/681
