### ISSUE TITLE
TypeError: this._meter.createSumObserver is not a function @opentelemetry/host-metrics 0.26.0

### ISSUE THREAD

**Issue by elbasan** [open-telemetry/opentelemetry-js-contrib#775]
### What version of OpenTelemetry are you using?
```
@opentelemetry/api": "^1.0.3",
@opentelemetry/api-metrics": "^0.27.0",
@opentelemetry/core": "^1.0.1",
@opentelemetry/exporter-jaeger": "^1.0.1",
@opentelemetry/exporter-prometheus": "^0.27.0",
@opentelemetry/host-metrics": "^0.26.0",
@opentelemetry/instrumentation-express": "^0.27.0",
@opentelemetry/instrumentation-graphql": "^0.27.0",
@opentelemetry/instrumentation-http": "^0.27.0",
@opentelemetry/sdk-metrics-base": "^0.27.0",
@opentelemetry/sdk-trace-base": "^1.0.1",
@opentelemetry/sdk-trace-node": "^1.0.1",
```
### What version of Node are you using?
v16.13.0

### What did you do?

```
import { PrometheusExporter } from '@opentelemetry/exporter-prometheus';
import { MeterProvider } from '@opentelemetry/sdk-metrics-base';
import { HostMetrics } from '@opentelemetry/host-metrics';

const exporter = new PrometheusExporter({ appendTimestamp: true }, () => {
  console.log('prometheus scrape endpoint: http://localhost:9464/metrics');
});

const meterProvider = new MeterProvider({
  exporter,
  interval: 2000,
});

const metrics = new HostMetrics({ meterProvider, name: 'example-host-metrics' });
metrics.start();
```
### What did you expect to see?
CPU, Memory, and Network metrics should be exported to Prometheus.

### What did you see instead?
```
node_modules/@opentelemetry/host-metrics/build/src/metric.js:132: 
-> this._cpuTimeObserver = this._meter.createSumObserver(enums.METRIC_NAMES.CPU_TIME, { description: 'Cpu time in seconds', unit: 's' });

TypeError: this._meter.createSumObserver is not a function
    at HostMetrics._createMetrics (/node_modules/@opentelemetry/host-metrics/build/src/metric.js:132:45)
    at /node_modules/@opentelemetry/host-metrics/build/src/metric.js:173:18
```
I guess the error is happening here:
![image](https://user-images.githubusercontent.com/12799363/144603838-87ae0d6f-c543-404a-8efa-25d555213e48.png)

### Additional context

The project uses `apollo-graphql@3.1.2` and `typescript@^4.2.4`

**Comment by legendecas** [comment]
The version of @opentelemetry/host-metrics is not aligned with @opentelemetry/sdk-metrics-base and @opentelemetry/api-metrics. As the api-metrics is under work to reach the stable status, there might be breaking changes introduced on semver major bumps.

Either way, I'd believe we should update @opentelemetry/host-metrics to works with v0.27.0 as we already released @opentelemetry/api-metrics v0.27.0.

**Comment by elbasan** [comment]
@legendecas thank you very much for the help

**Comment by Rauno56** [comment]
Metrics SDK and API are still win works. Tune in here: https://github.com/open-telemetry/opentelemetry-js/projects/16
