### ISSUE TITLE
TypeError: tracer.getCurrentSpan is not a function

### ISSUE THREAD

**Issue by Hongbo-Miao** [open-telemetry/opentelemetry-js-contrib#314]
### What version of OpenTelemetry are you using?
0.15.0

### What version of Node are you using?
14.15.1

### What did you do?
If possible, provide a recipe for reproducing the error.
After upgrading OpenTelemetry to 0.15.0

### What did you expect to see?
The app not crash.

### What did you see instead?
```
TypeError: tracer.getCurrentSpan is not a function
    at Redis.sendCommand (/my-app/server/node_modules/@opentelemetry/plugin-ioredis/build/src/utils.js:67:20)
    at Redis.info (/my-app/server/node_modules/ioredis/built/commander.js:111:25)
    at Redis._readyCheck (/my-app/server/node_modules/ioredis/built/redis/index.js:464:10)
    at Socket.<anonymous> (/my-app/server/node_modules/ioredis/built/redis/event_handler.js:54:18)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1132:10)
    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:129:14)
```

### Additional context
This is because of this change https://github.com/open-telemetry/opentelemetry-js/pull/1764
All plugins using `getCurrentSpan` need to update to be compatible to new OpenTelemetry 0.15.0

**Comment by Flarna** [comment]
The plugins in this repo have not yet been updated to 0.15.0. Please use 0.14.0 until a new release is done.

**Comment by Hongbo-Miao** [comment]
Thanks @Flarna !
