### ISSUE TITLE
[instrumentation-mongodb] breaks build ((TS2304) Cannot find name 'Document')

### ISSUE THREAD

**Issue by sberz** [open-telemetry/opentelemetry-js-contrib#1639]
### What version of OpenTelemetry are you using?
```
@opentelemetry/api 1.4.1
@opentelemetry/auto-instrumentations-node 0.39.0 (uses @opentelemetry/instrumentation-mongodb 0.36.1)
@opentelemetry/sdk-node 0.41.2
```

### What version of Node are you using?
18.17.1

### What did you do?

1. I tried to upgrade the following OpenTelemetry packages:
```diff
-      '@opentelemetry/auto-instrumentations-node': ^0.36.4
-      '@opentelemetry/sdk-node': ^0.36.0
+      '@opentelemetry/auto-instrumentations-node': ^0.39.0
+      '@opentelemetry/sdk-node': ^0.41.2
```
2. Tried to build my application (Typescript strict mode; `skipLibCheck: false`)

### What did you expect to see?
The application should still build.

### What did you see instead?
With the new versions I can no longer build our application and get the following error:
```
[typescript] Error: common/temp/node_modules/.pnpm/@opentelemetry+instrumentation-mongodb@0.36.1_@opentelemetry+api@1.4.1/node_modules/@opentelemetry/instrumentation-mongodb/build/src/types.d.ts:49:27 - (TS2304) Cannot find name 'Document'.
Encountered 1 errors:
  [typescript] common/temp/node_modules/.pnpm/@opentelemetry+instrumentation-mongodb@0.36.1_@opentelemetry+api@1.4.1/node_modules/@opentelemetry/instrumentation-mongodb/build/src/types.d.ts:49:27 - (TS2304) Cannot find name 'Document'.
Error: Encountered TypeScript error
```
### Additional context

Seems like https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1190 got reintroduced by https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1170

Removing [the seemingly unused `V4Connection` type from `types.d.ts`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-mongodb/src/types.ts#L73-L82) fixes the build for me.
